# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 280)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 160, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 160, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("png")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 90, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("png")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(300, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 210, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 210, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(300, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.choose_path)  # type: ignore
        self.pushButton_2.clicked.connect(Form.rename)  # type: ignore
        self.comboBox_2.currentIndexChanged["QString"].connect(Form.format2_change)  # type: ignore
        self.comboBox.currentIndexChanged["QString"].connect(Form.format1_change)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Path"))
        self.pushButton.setText(_translate("Form", "選擇資料夾"))
        self.comboBox_2.setItemText(0, _translate("Form", "png"))
        self.comboBox_2.setItemText(1, _translate("Form", "jpg"))
        self.comboBox_2.setItemText(2, _translate("Form", "pdf"))
        self.comboBox_2.setItemText(3, _translate("Form", "txt"))
        self.comboBox_2.setItemText(4, _translate("Form", "zip"))
        self.comboBox_2.setItemText(5, _translate("Form", "rar"))
        self.comboBox_2.setItemText(6, _translate("Form", "7z"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "請輸入檔案名稱"))
        self.pushButton_2.setText(_translate("Form", "更改"))
        self.comboBox.setItemText(0, _translate("Form", "png"))
        self.comboBox.setItemText(1, _translate("Form", "jpg"))
        self.comboBox.setItemText(2, _translate("Form", "pdf"))
        self.comboBox.setItemText(3, _translate("Form", "txt"))
        self.comboBox.setItemText(4, _translate("Form", "zip"))
        self.comboBox.setItemText(5, _translate("Form", "rar"))
        self.comboBox.setItemText(6, _translate("Form", "7z"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
