from PyQt5 import QtWidgets
from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication
from PyQt5.QtGui import QFont


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 280)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QRect(20, 160, 261, 31))
        font = QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QRect(300, 160, 81, 31))
        font = QFont()
        font.setFamily("微軟正黑體")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QRect(20, 20, 261, 41))
        font = QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QRect(20, 90, 261, 41))
        font = QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QRect(300, 90, 81, 31))
        font = QFont()
        font.setFamily("微軟正黑體")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QRect(20, 210, 261, 41))
        font = QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QRect(300, 210, 81, 51))
        font = QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QRect(300, 20, 81, 31))
        font = QFont()
        font.setFamily("微軟正黑體")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.choose_path)  # type: ignore
        self.pushButton_2.clicked.connect(Form.rename)  # type: ignore
        self.comboBox_2.currentIndexChanged["QString"].connect(Form.format2_change)  # type: ignore
        self.comboBox.currentIndexChanged["QString"].connect(Form.format1_change)  # type: ignore
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Path"))
        self.pushButton.setText(_translate("Form", "選擇資料夾"))
        self.comboBox_2.setItemText(0, _translate("Form", "png"))
        self.comboBox_2.setItemText(1, _translate("Form", "jpg"))
        self.comboBox_2.setItemText(2, _translate("Form", "pdf"))
        self.comboBox_2.setItemText(3, _translate("Form", "txt"))
        self.comboBox_2.setItemText(4, _translate("Form", "zip"))
        self.comboBox_2.setItemText(5, _translate("Form", "rar"))
        self.comboBox_2.setItemText(6, _translate("Form", "7z"))
        self.lineEdit.setPlaceholderText(_translate("Form", "原始檔案格式"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "輸出檔案格式"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "請輸入檔案名稱"))
        self.pushButton_2.setText(_translate("Form", "更改"))
        self.comboBox.setItemText(0, _translate("Form", "png"))
        self.comboBox.setItemText(1, _translate("Form", "jpg"))
        self.comboBox.setItemText(2, _translate("Form", "pdf"))
        self.comboBox.setItemText(3, _translate("Form", "txt"))
        self.comboBox.setItemText(4, _translate("Form", "zip"))
        self.comboBox.setItemText(5, _translate("Form", "rar"))
        self.comboBox.setItemText(6, _translate("Form", "7z"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
